import {
  BcpiFileSchema,
  BuildingCostsFileSchema,
  AltusBenchmarksFileSchema,
  CanadaBuysFileSchema,
  ConstructionDurationsFileSchema,
  OverrunReferenceFileSchema,
  ParkFeaturesFileSchema,
  RefDataSchema,
  RegionalFactorsFileSchema,
  StructuresFileSchema,
  UnitPricesFileSchema,
  ZoneRulesFileSchema,
  type BcpiFile,
  type BuildingCostsFile,
  type AltusBenchmarksFile,
  type CanadaBuysFile,
  type ConstructionDurationsFile,
  type OverrunReferenceFile,
  type ParkFeaturesFile,
  type RefData,
  type RegionalFactorsFile,
  type StructuresFile,
  type UnitPricesFile,
  type ZoneRulesFile,
} from "@/lib/schemas";
import buildingCostsJson from "./building-costs.json";
import overrunReferenceJson from "./overrun-reference.json";
import parkFeaturesJson from "./park-features.json";
import regionalFactorsJson from "./regional-factors.json";
import structuresJson from "./structures.json";
import canadabuysAwardsJson from "./public/canadabuys-awards.json";
import constructionDurationsJson from "./public/construction-durations.json";
import altusBenchmarksJson from "./altus-benchmarks.json";
import statcanBcpiJson from "./public/statcan-bcpi.json";
import unitPricesJson from "./unit-prices.json";
import waterlooRulesJson from "./zoning/waterloo-rules.json";

// Seed data (SPEC 8), parsed once so consumers get typed, validated objects.
// Sample data only: every file has `meta.sample: true`. Treat as read-only.

export const unitPrices: UnitPricesFile =
  UnitPricesFileSchema.parse(unitPricesJson);
export const buildingCosts: BuildingCostsFile =
  BuildingCostsFileSchema.parse(buildingCostsJson);
export const parkFeatures: ParkFeaturesFile =
  ParkFeaturesFileSchema.parse(parkFeaturesJson);
export const structures: StructuresFile =
  StructuresFileSchema.parse(structuresJson);
export const regionalFactors: RegionalFactorsFile =
  RegionalFactorsFileSchema.parse(regionalFactorsJson);
export const overrunReference: OverrunReferenceFile =
  OverrunReferenceFileSchema.parse(overrunReferenceJson);

/** Everything `computeEstimate` needs (TEAM.md 3.3). */
export const refData: RefData = RefDataSchema.parse({
  unitPrices,
  buildingCosts,
  parkFeatures,
  structures,
  regionalFactors,
  overrunReference,
});

// Real public data (SPEC 8.1), generated by scripts/ and committed.

/** Statistics Canada BCPI, table 18-10-0289-01 (Ontario CMAs + composite). */
export const statcanBcpi: BcpiFile = BcpiFileSchema.parse(statcanBcpiJson);

/** CanadaBuys federal construction awards in Ontario. Market evidence only. */
export const canadabuysAwards: CanadaBuysFile =
  CanadaBuysFileSchema.parse(canadabuysAwardsJson);

/** Altus Group 2026 road benchmarks ($/m). Cross-check in the market evidence card only. */
export const altusBenchmarks: AltusBenchmarksFile =
  AltusBenchmarksFileSchema.parse(altusBenchmarksJson);

/** Construction duration vs contract value, fitted on CanadaBuys contracts (scripts/fetch-durations.ts). */
export const constructionDurations: ConstructionDurationsFile =
  ConstructionDurationsFileSchema.parse(constructionDurationsJson);

/** City of Waterloo Zoning By-law 2018-050 regulations per zone (advisory checks only). */
export const waterlooZoneRules: ZoneRulesFile =
  ZoneRulesFileSchema.parse(waterlooRulesJson);
